development:
  # adapter: async
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: async

production:
  adapter: redis
  url: redis://h:pe789d50a1aa8ff07b5e2ea5a6c6563eac623f0b79630a0344a82f8bb3ad29636@ec2-3-226-35-239.compute-1.amazonaws.com:29529
  #channel_prefix: PhonePal_production


# The Redis adapter requires users to provide a URL pointing to the Redis server. 
# Additionally, a channel_prefix may be provided to avoid channel 
# name collisions when using the same Redis server for multiple applications. 
